services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: order_app
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "uv run --active python manage.py migrate && uv run --active python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DEBUG=True

volumes:
  postgres_data: